export const CREATE_USER = 'CREATE_USER';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SYNC_PROJECTS = 'SYNC_PROJECTS';
export const SAVE_CURRENT_PROJECT = 'SAVE_CURRENT_PROJECT';